# Generated by Django 2.1.5 on 2020-04-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0006_auto_20200402_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='sendbyemail',
            field=models.BooleanField(default=False, verbose_name='Send by email?'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='If you want to send the result via email, please enter an email address here.', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
