# Generated by Django 2.1.5 on 2020-04-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0007_auto_20200403_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendbyemail', models.BooleanField(default=False, verbose_name='Send prediction to email?')),
            ],
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='sendbyemail',
            field=models.BooleanField(default=False, verbose_name='Send prediction to email?'),
        ),
    ]
