# Generated by Django 3.0.3 on 2020-02-26 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0002_auto_20200226_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='kmer_size',
            field=models.IntegerField(blank=True, help_text='If you have kmers with different length, please keep this box blank.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Kmer size (optional)'),
        ),
    ]
