# Generated by Django 2.1.5 on 2020-04-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0004_auto_20200226_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='kmer',
            field=models.CharField(blank=True, help_text='Enter one or more kmer sizes here if you want to train the model with specific kmer size. Please separate each kmer size by a comma.', max_length=200, null=True, verbose_name='Kmer size'),
        ),
    ]
