# Generated by Django 2.1.5 on 2020-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0011_auto_20200607_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='If you want to send the result via email, please enter a valid email address here. E.g. xxxxx@gmail.com', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
