# Generated by Django 3.1.5 on 2021-01-26 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(upload_to='userfiles/', verbose_name='File')),
                ('labelpath', models.FileField(blank=True, upload_to='userfiles/', verbose_name='File')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlmodels', models.CharField(choices=[('K-Means Clustering', (('unsupervisedKmeans', 'Unsupervised K-Means'), ('semisupervisedKmeans', 'Semi-supervised K-Means'))), ('Gaussian Mixture Model', (('unsupervisedGMM', 'Unsupervised GMM'), ('semisupervisedGMM', 'Semi-supervised GMM'))), ('Spectral Clustering', (('unsupervisedSpectralClustering', 'Unsupervised Spectral Clustering'), ('semisupervisedSpectralClustering', 'Semi-supervised Spectral Clustering')))], default='unsupervisedKmeans', max_length=100, verbose_name='Model')),
                ('sendbyemail', models.BooleanField(default=False, verbose_name='Send prediction to email?')),
                ('email', models.EmailField(blank=True, help_text='If you want to send the result via email, please enter a valid email address here. E.g. xxxxx@gmail.com', max_length=254, null=True, verbose_name='Email')),
                ('parameters', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileListInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelist', models.ManyToManyField(blank=True, to='mlmodel.FileInfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
