# Generated by Django 2.1.5 on 2020-04-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0008_auto_20200403_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='kmer',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='sendbyemail',
        ),
        migrations.AddField(
            model_name='predictinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='If you want to send the result via email, please enter an email address here.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='predictinfo',
            name='kmer',
            field=models.CharField(blank=True, help_text='Enter one or more kmer sizes here if you want to train the model with specific kmer size. Please separate each kmer size by a comma.', max_length=200, null=True, verbose_name='Kmer size'),
        ),
        migrations.AddField(
            model_name='predictinfo',
            name='mlmodels',
            field=models.CharField(choices=[('kmeans', 'kmeans'), ('choice2', 'choice2'), ('choice3', 'choice3')], default='kmeans', max_length=10),
        ),
    ]
