# Generated by Django 2.1.5 on 2020-06-07 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0010_auto_20200607_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='If you want to send the result via email, please enter a valid email address here.', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address, e.g. xxxxx@gmail.com')], verbose_name='Email'),
        ),
    ]
