# Generated by Django 2.1.5 on 2020-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0012_auto_20200607_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileListInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelist', models.ManyToManyField(blank=True, to='mlmodel.FileInfo')),
            ],
        ),
    ]
