# Generated by Django 2.1.5 on 2020-06-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0013_filelistinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelistinfo',
            name='alignment',
            field=models.CharField(choices=[('aligned', 'aligned'), ('unaligned', 'unaligned')], default='unaligned', max_length=30),
        ),
    ]
