# Generated by Django 2.1.5 on 2020-07-24 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0016_auto_20200712_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictinfo',
            name='parameters',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictinfo',
            name='mlmodels',
            field=models.CharField(choices=[('K-Means Clustering', (('kmeansPCA', 'PCA'), ('kmeansTSNE', 'TSNE'), ('kmeansMeanshiftPCA', 'Meanshift PCA'), ('kmeansMeanshiftTSNE', 'Meanshift TSNE'))), ('Gaussian Mixture Model', (('gmm', 'GMM'),))], default='kmeansPCA', max_length=30, verbose_name='Model'),
        ),
    ]
