# Generated by Django 2.1.5 on 2020-08-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0018_remove_predictinfo_kmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelistinfo',
            name='alignment',
        ),
    ]
