# Generated by Django 2.1.5 on 2020-09-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0019_remove_filelistinfo_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictinfo',
            name='mlmodels',
            field=models.CharField(choices=[('K-Means Clustering', (('kmeansPCA', 'PCA'), ('kmeansTSNE', 'TSNE'), ('kmeansMeanshiftPCA', 'Meanshift PCA'), ('kmeansMeanshiftTSNE', 'Meanshift TSNE'))), ('Gaussian Mixture Model', (('gmm', 'GMM'),)), ('Spectral Clustering', (('spectralClustering', 'Spectral Clustering'),))], default='kmeansPCA', max_length=30, verbose_name='Model'),
        ),
    ]
