# Generated by Django 3.1.2 on 2020-10-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0020_auto_20200929_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='kmer_size',
        ),
    ]
