# Generated by Django 3.1.2 on 2020-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0021_remove_fileinfo_kmer_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='labelpath',
            field=models.FileField(blank=True, upload_to='userfiles/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='predictinfo',
            name='mlmodels',
            field=models.CharField(choices=[('K-Means Clustering', (('kmeansPCA', 'PCA'), ('kmeansTSNE', 'TSNE'), ('kmeansMeanshiftPCA', 'Meanshift PCA'), ('kmeansMeanshiftTSNE', 'Meanshift TSNE'))), ('Gaussian Mixture Model', (('gmm', 'GMM'),)), ('Spectral Clustering', (('unsupervisedSpectralClustering', 'Unsupervised Spectral Clustering'), ('semisupervisedSpectralClustering', 'Semi-supervised Spectral Clustering')))], default='kmeansPCA', max_length=100, verbose_name='Model'),
        ),
    ]
