# Generated by Django 3.1.2 on 2020-11-29 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlmodel', '0022_auto_20201112_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filelistinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predictinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predictinfo',
            name='mlmodels',
            field=models.CharField(choices=[('K-Means Clustering', (('kmeansPCA', 'PCA'), ('kmeansTSNE', 'TSNE'), ('kmeansMeanshiftPCA', 'Meanshift PCA'), ('kmeansMeanshiftTSNE', 'Meanshift TSNE'))), ('Gaussian Mixture Model', (('unsupervisedGMM', 'Unsupervised GMM'), ('semisupervisedGMM', 'Semi-supervised GMM'))), ('Spectral Clustering', (('unsupervisedSpectralClustering', 'Unsupervised Spectral Clustering'), ('semisupervisedSpectralClustering', 'Semi-supervised Spectral Clustering')))], default='kmeansPCA', max_length=100, verbose_name='Model'),
        ),
    ]
