# Generated by Django 2.1.5 on 2020-04-02 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0005_auto_20200402_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='If you want to send the result to email, please enter an email address here.', max_length=254, null=True, validators=[django.core.validators.EmailValidator('e.g. xxx@gmail.com')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='filepath',
            field=models.FileField(upload_to='userfiles/', verbose_name='File'),
        ),
    ]
