# Generated by Django 2.1.5 on 2020-06-07 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0009_auto_20200416_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='If you want to send the result via email, please enter an email address here.', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='e.g. xxxxx@gmail.com')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='predictinfo',
            name='mlmodels',
            field=models.CharField(choices=[('kmeans', 'kmeans'), ('kmeansPCA', 'kmeansPCA'), ('kmeansTSNE', 'kmeansTSNE'), ('kmeansMeanshiftPCA', 'kmeansMeanshiftPCA'), ('kmeansMeanshiftTSNE', 'kmeansMeanshiftTSNE')], default='kmeans', max_length=30),
        ),
    ]
