# R script for manuscript plots

## Spectral clustering

Read data:
```{r}
#dat = read.table("spectral_output/spectral_export_PCA.csv", header=TRUE, sep=",")
dat = read.table("../scripts/spectral/labels_PCA.csv", header=TRUE, sep=",")
colnames(dat) <- c("idx","label")
str(dat)

## --------------------------------------------
## 10 percent labels observed (both classes)
## --------------------------------------------

tmpdat = read.table("../scripts/spectral/ten_percent_PCA.csv", header=TRUE, sep=",")
str(tmpdat)
#tmpdat2 = read.table("../scripts/spectral/spectral_result_semi_10_dis.csv", header=TRUE, sep=",")
#str(tmpdat2)

## add column to dat
dat$pred10dis = tmpdat$label
dat$pred10dis.x1 = tmpdat$dimension1
dat$pred10dis.x2 = tmpdat$dimension2

## --------------------------------------------
## 10 percent labels observed (only 0)
## --------------------------------------------

tmpdat = read.table("../scripts/spectral/ten_percent_only0s_PCA.csv", header=TRUE, sep=",")
str(tmpdat)

## add column to dat
dat$pred10dis0 = tmpdat$label
dat$pred10dis0.x1 = tmpdat$dimension1
dat$pred10dis0.x2 = tmpdat$dimension2

## --------------------------------------------
## 50 percent labels observed (discretize)
## --------------------------------------------
tmpdat = read.table("../scripts/spectral/fifty_percent_discretize_PCA.csv", header=TRUE, sep=",")
str(tmpdat)

## add column to dat
dat$pred50dis = tmpdat$label
dat$pred50dis.x1 = tmpdat$dimension1
dat$pred50dis.x2 = tmpdat$dimension2

## --------------------------------------------
## 50 percent labels observed (kmeans)
## --------------------------------------------
tmpdat = read.table("../scripts/spectral/fifty_percent_kmeans_PCA.csv", header=TRUE, sep=",")
str(tmpdat)

## add column to dat
dat$pred50k = tmpdat$label
dat$pred50k.x1 = tmpdat$dimension1
dat$pred50k.x2 = tmpdat$dimension2

## --------------------------------------------
## Unsupervised
## --------------------------------------------
tmpdat = read.table("../scripts/spectral/unsupervised_PCA.csv", header=TRUE, sep=",")
str(tmpdat)

## add column to dat (original results)
dat$pred.unsup = tmpdat$label
dat$predunsup.x1 = tmpdat$dimension1
dat$predunsup.x2 = tmpdat$dimension2



## Data has all columns:
str(dat)

## Computed raw accuracies:
n = length(dat$label)
1-sum(abs(dat$label - dat$pred10dis0))/n
1-sum(abs(dat$label - dat$pred10dis))/n
1-sum(abs(dat$label - dat$pred50dis))/n
1-sum(abs(dat$label - dat$pred50k))/n
1-sum(abs(dat$label - dat$pred.unsup))/n
``` 

Plots:
```{r}
library(ggplot2)

p = ggplot(dat,aes(x=pred10dis.x1, y=pred10dis.x2, color=as.factor(pred10dis),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("Spectral 10% labels (both classes)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p2 = ggplot(dat,aes(x=pred10dis0.x1, y=pred10dis0.x2, color=as.factor(pred10dis0),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("Spectral 10% labels (only 0's)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p3 = ggplot(dat,aes(x=pred50dis.x1, y=pred50dis.x2, color=as.factor(pred50dis),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("Spectral 50% labels (discretize)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p4 = ggplot(dat,aes(x=pred50k.x1, y=pred50k.x2, color=as.factor(pred50k),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("Spectral 50% labels (k-means)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p5 = ggplot(dat,aes(x=predunsup.x1, y=predunsup.x2, color=as.factor(pred.unsup),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab("PC2")+ ggtitle("Spectral 0% labels (unsupervised)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))
p
p2
p3
p4
p5

## Saving plots
pdf("spectral-10dis.pdf",width=5,height=5)
p
dev.off()

pdf("spectral-10dis0.pdf",width=5,height=5)
p2
dev.off()

pdf("spectral-50dis.pdf",width=5,height=5)
p3
dev.off()

pdf("spectral-50k.pdf",width=5,height=5)
p4
dev.off()

pdf("spectral-unsup.pdf",width=5,height=5)
p5
dev.off()
```

## k-means

Reading the data:
```{r}
dat0 = read.table("../scripts/nonNotebookFiles/test0_PCA.csv", header=TRUE, sep=",")
str(dat0)
dat0$PC1 = dat0$X0
dat0$PC2 = dat0$X1
dat0$pred0 = dat0$labels
dat0$label = dat$label ## using spectral data for the true labels of all

tmpdat = read.table("../scripts/nonNotebookFiles/test10_PCA.csv", header=TRUE, sep=",")
str(tmpdat)
dat0$pred10 = tmpdat$labels
dat0$pred10.x1 = tmpdat$X0
dat0$pred10.x2 = tmpdat$X1

tmpdat = read.table("../scripts/nonNotebookFiles/test10_0_PCA.csv", header=TRUE, sep=",")
str(tmpdat)
dat0$pred10.0 = tmpdat$labels
dat0$pred10.0.x1 = tmpdat$X0
dat0$pred10.0.x2 = tmpdat$X1

tmpdat = read.table("../scripts/nonNotebookFiles/test50_PCA.csv", header=TRUE, sep=",")
str(tmpdat)
dat0$pred50 = tmpdat$labels
dat0$pred50.x1 = tmpdat$X0
dat0$pred50.x2 = tmpdat$X1

## Data has all columns:
str(dat0)

## Computed raw accuracies:
n = length(dat0$label)
1-sum(abs(dat0$label - dat0$pred0))/n
1-sum(abs(dat0$label - dat0$pred10.0))/n
1-sum(abs(dat0$label - dat0$pred10))/n
1-sum(abs(dat0$label - dat0$pred50))/n
```

Plots:
```{r}
library(ggplot2)

p = ggplot(dat0,aes(x=PC1, y=PC2, color=as.factor(pred0),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("k-means 0% labels (unsupervised)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p2 = ggplot(dat0,aes(x=pred10.x1, y=pred10.x2, color=as.factor(pred10),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("k-means 10% labels (both classes)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p2.0 = ggplot(dat0,aes(x=pred10.x1, y=pred10.x2, color=as.factor(pred10.0),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("k-means 10% labels (only 0's)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p3 = ggplot(dat0,aes(x=pred50.x1, y=pred50.x2, color=as.factor(pred50),shape=as.factor(label)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("k-means 50% labels")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p
p2
p2.0
p3

## Saving plots
pdf("kmeans-0.pdf",width=5,height=5)
p
dev.off()

pdf("kmeans-10.pdf",width=5,height=5)
p2
dev.off()

pdf("kmeans-10-0.pdf",width=5,height=5)
p2.0
dev.off()

pdf("kmeans-50.pdf",width=5,height=5)
p3
dev.off()
```

## GMM clustering

Reading data:
```{r}
dat = read.table("../scripts/gmm/actual_labels.csv", header=TRUE, sep=",")
str(dat)
dat$target = dat$Labels

tmpdat = read.table("../scripts/gmm/predictions_unsup.csv", header=TRUE, sep=",")
str(tmpdat)
tmpdat2 = read.table("../scripts/gmm/pca_unsup.csv", header=TRUE, sep=",")
str(tmpdat2)
dat$pred0 = tmpdat$Labels
dat$pred0.x1 = tmpdat2$principal.Component.1
dat$pred0.x2 = tmpdat2$Principal.Component.2

tmpdat = read.table("../scripts/gmm/predictions_10%_bestModel.csv", header=TRUE, sep=",")
str(tmpdat)
tmpdat2 = read.table("../scripts/gmm/pca_10%.csv", header=TRUE, sep=",")
str(tmpdat2)
dat$pred10 = tmpdat$Labels
dat$pred10.x1 = tmpdat2$principal.Component.1
dat$pred10.x2 = tmpdat2$Principal.Component.2

tmpdat = read.table("../scripts/gmm/predictions_10%_only0s_bestModel.csv", header=TRUE, sep=",")
str(tmpdat)
tmpdat2 = read.table("../scripts/gmm/pca_10%_only0.csv", header=TRUE, sep=",")
str(tmpdat2)
dat$pred10.0 = tmpdat$Labels
dat$pred10.0.x1 = tmpdat2$principal.Component.1
dat$pred10.0.x2 = tmpdat2$Principal.Component.2


tmpdat = read.table("../scripts/gmm/predictions_50%_bestModel.csv", header=TRUE, sep=",")
str(tmpdat)
tmpdat2 = read.table("../scripts/gmm/pca_50%.csv", header=TRUE, sep=",")
str(tmpdat2)
dat$pred50 = tmpdat$Labels
dat$pred50.x1 = tmpdat2$principal.Component.1
dat$pred50.x2 = tmpdat2$Principal.Component.2


## Data has all columns:
str(dat)

## Computed raw accuracies:
n = length(dat$target)
1-sum(abs(dat$target - dat$pred0))/n
1-sum(abs(dat$target - dat$pred10))/n
1-sum(abs(dat$target - dat$pred10.0))/n
1-sum(abs(dat$target - dat$pred50))/n
```

Plots:
```{r}
library(ggplot2)

p = ggplot(dat,aes(x=pred0.x1, y=pred0.x2, color=as.factor(pred0),shape=as.factor(target)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("GMM 0% labels (unsupervised)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p2 = ggplot(dat,aes(x=pred10.x1, y=pred10.x2, color=as.factor(pred10),shape=as.factor(target)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("GMM 10% labels (both classes)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p2.0 = ggplot(dat,aes(x=pred10.0.x1, y=pred10.0.x2, color=as.factor(pred10.0),shape=as.factor(target)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("GMM 10% labels (only 0's)")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p3 = ggplot(dat,aes(x=pred50.x1, y=pred50.x2, color=as.factor(pred50),shape=as.factor(target)))+geom_point(cex=4, alpha=0.65)+
   xlab("PC1") + ylab(" ")+ ggtitle("GMM 50% labels")+
   theme(
    plot.title = element_text(hjust=0.5, size=rel(1.6)),
    axis.title.x = element_text(size=rel(1.4)),
    axis.title.y = element_text(size=rel(1.4), angle=90, vjust=0.5, hjust=0.5),
    axis.text.x = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    axis.text.y = element_text(colour="grey", size=rel(1.2), angle=0, hjust=.5, vjust=.5, face="plain"),
    legend.text=element_text(size=rel(1.2)), legend.title=element_text(size=rel(1.5)),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"),
    legend.position="none"
  )+
  scale_color_manual(values=c("#56B4E9", "#009E73"))

p
p2
p2.0
p3

## Saving plots
pdf("gmm-0.pdf",width=5,height=5)
p
dev.off()

pdf("gmm-10.pdf",width=5,height=5)
p2
dev.off()

pdf("gmm-10-0.pdf",width=5,height=5)
p2.0
dev.off()

pdf("gmm-50.pdf",width=5,height=5)
p3
dev.off()
```

For this case, there is one sequence that is weird. The PCs are much bigger compared to other sequences.
```{r}
dat[dat$pred50.x1>10,]
```
